services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306" # Bind MySQL to localhost for external access
    volumes:
      - mysql-data:/var/lib/mysql
    restart: on-failure
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 3
    networks:
      - internal_network

  ugracing_bot:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    depends_on:
      mysql:
        condition: service_healthy
    restart: on-failure
    volumes:
      - "./Gryphon Racing Administrative/Team Roster/Verification Team Roster.xlsx:/usr/src/app/resources/verification.xlsx"
      - "./docker_target:/usr/src/app/target"
      - "./src:/usr/src/app/src"
      - "./Cargo.toml:/usr/src/app/Cargo.toml"
      - "./Cargo.lock:/usr/src/app/Cargo.lock"
    networks:
      - internal_network
    ports:
      - "587:587" # Bind SMTP port to host
      - "465:465" # Optional SSL port for SMTP

volumes:
  mysql-data:

networks:
  internal_network:
    driver: bridge