services:
  mosquitto:
    image: eclipse-mosquitto:2.0
    container_name: mosquitto
    ports:
      - "1883:1883"
    volumes: 
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf
      - mosquitto-data:/mosquitto/data
      - mosquitto-log:/mosquitto/log
    restart: unless-stopped

  discord-bot:
    build: .
    container_name: discord-bot
    env_file: .env
    volumes:
      - ./comps.json:/app/comps.json
    depends_on:
      - mosquitto
    restart: unless-stopped

  mqtt-logger: 
    build: .
    container_name: mqtt-logger
    command: python backend/mqtt.py
    env_file: .env
    depends_on:
      - mosquitto
      - influxdb
    restart: unless-stopped

  influxdb:
    image: influxdb:2.7
    environment:
      DOCKER_INFLUXDB_INIT_MODE: setup
      DOCKER_INFLUXDB_INIT_USERNAME: ${INFLUXDB_USERNAME}
      DOCKER_INFLUXDB_INIT_PASSWORD: ${INFLUXDB_PASSWORD}
      DOCKER_INFLUXDB_INIT_ORG: ${INFLUXDB_ORG}
      DOCKER_INFLUXDB_INIT_BUCKET: ${INFLUXDB_BUCKET}
      DOCKER_INFLUXDB_INIT_ADMIN_TOKEN: ${INFLUXDB_TOKEN}
    ports:
    - "8086:8086"
    volumes: 
      - influxdb-data:/var/lib/influxdb2
    restart: unless-stopped

volumes:
  mosquitto-data:
  mosquitto-log:
  influxdb-data:
