services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
    ports:
      - "3306:3306" # Bind MySQL to localhost for external access
    volumes:
      - mysql-data:/var/lib/mysql
    restart: on-failure
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 3
    networks:
      - internal_network

  ugracing_bot:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    depends_on:
      mysql:
        condition: service_healthy
    restart: on-failure
    volumes:
      - "./Gryphon Racing Administrative/Team Roster/:/app/resources/"
    networks:
      - internal_network

volumes:
  mysql-data:

networks:
  internal_network:
    driver: bridge