name: Backup monthly audit logs

on:
  workflow_dispatch:
  schedule:
    - cron: '0 5 1 * *' # runs monthly, on the 1st at midnight EST

jobs:
  Fetch-Logs:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3

      - name: Install dependencies
        run: npm i

      - name: Compile typescript
        run: npx tsc
        env:
          DISCORD_BOT_TOKEN: ${{ secrets.DISCORD_BOT_TOKEN }}
          DISCORD_GUILD_ID: ${{ secrets.DISCORD_GUILD_ID }}

      - name: Upload Archive
        uses: actions/upload-artifact@v3
        with:
          name: logs
          path: logs.json
