name: Deploy GRacingBot

on:
  workflow_dispatch:
  push:

jobs:
  build:
    # Currently we deploy via docker on our shop server, set up has a runner
    runs-on: [ self-hosted, Linux, X64 ]
    steps:
      - uses: actions/checkout@v3

      # I installed docker using the docs here: https://docs.docker.com/desktop/install/ubuntu/
      - name: Deploy with Docker
        env:
          DISCORD_BOT_TOKEN: ${{ secrets.DISCORD_BOT_TOKEN }}
          DISCORD_APPLICATION_ID: ${{ secrets.DISCORD_APPLICATION_ID }}
          DISCORD_GUILD_ID: ${{ secrets.DISCORD_GUILD_ID }}
        run: |
          docker build GRacingBot --tag gracingbot
          docker stop GRacingBot || true # It's okay if these fail, as the bot might not be active or existant
          docker rm GRacingBot || true
          docker run --restart unless-stopped --detach --name GRacingBot gracingbot
