name: Lint, Formatting & Type Check

on:
  push:

jobs:
  Lint-Type-Build-Check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3

      - name: Install dependencies
        run: npm i

        # Run all the checks, and report all the results
      - name: Lint check
        if: always()
        run: npm run lint-check

      - name: Type Check
        if: always()
        run: npm run type-check

      - name: Compile TypeScript
        if: always()
        run: npm run build
